mas 'Command & Conquer™: Generals Deluxe Edition', id: 912423770
mas 'Galaxy on Fire 2™ Full HD', id: 452222956
mas 'Homeworld Remastered Collection', id: 991804858
mas 'Mini Metro', id: 1047760200
mas 'RollerCoaster Tycoon 3 Platinum', id: 549294099
mas 'SimCity™ 4 Deluxe Edition', id: 804079949
mas 'XCOM Enemy Unknown - Elite Edition', id: 594787538
