brew 'phantomjs'
brew 'watch'

cask 'dropbox'
cask 'launchbar'
cask 'nvalt'
cask 'rowanj-gitx'
cask 'sublime-text'
cask 'textmate'
cask 'things'
cask 'vmware-fusion'

mas '1Password', id: 443987910
mas 'GIF Brewery', id: 1081413713
mas 'Markoff', id: 1084713122
mas 'xScope', id: 889428659
